version: "3"

services:
  postgres:
    container_name: "postgres-help"
    image: "postgres:13-alpine"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: "help"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "hope:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

volumes:
  hope:
